name: CI
on: [push, pull_request]
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                  - ubuntu-20.04
                  - windows-2022

        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up MinGW
            if: runner.os == 'Windows'
            uses: egor-tensin/setup-mingw@v2
            with:
                version: 8.1.0
                platform: x64
                cc: 1

          - name: Install GCC 8
            if: runner.os == 'Linux'
            uses: egor-tensin/setup-gcc@v1.3
            with:
                version: 8
                platform: x64
                cc: 1

          - run: c++ --version

          - name: Install Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.x'
                architecture: x64

          - run: python --version

          - name: Compile and run tests
            run: cd test && python main.py
